# Generated by Django 6.0.4 on 2026-07-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
